### ISSUE TITLE
Ajouter la possibilité d'enregistrer des plages de temps pour les utilisateurs

### ISSUE THREAD

**Issue by shordeaux** [EtincelleCoworking/intranet#14]
cela facilitera la facturation en fin de mois

**Comment by redfish31** [comment]
Tu entends par là un select "heure de début" et un pour "heure de fin" ?

**Comment by redfish31** [comment]
ping @shordeaux

**Comment by shordeaux** [comment]
Ajouter une section "Temps passé" affichant une liste avec:
- date
- ressource
- heure début
- heure fin
- temps passé

avec en haut un tableau récap:
- ressource
- durée totale
- tarif

la possibilité d'ajouter/modifier/supprimer des créneaux temps

dans un second temps ces lignes seront mises automatiquement via le système d'Olivier
