### ISSUE TITLE
Revoir la présentation des dépenses

### ISSUE THREAD

**Issue by shordeaux** [EtincelleCoworking/intranet#31]
Un seul tableau avec une ligne par charge
- la description reprends les différentes charge_items (1 par ligne)
- une colonne total HT et une total TVA (sans rentrer dans le détail des taux)
- segmentation mois par mois
- récapitulatif dans la page du total par taux de TVA et de la TVA associée pour faciliter la déclaration de TVA
- trier les lignes par date
- lien pour télécharger le PJ

**Comment by redfish31** [comment]
Je crée un nouveau ticket pour la partie "filtre par mois" : #37
