### ISSUE TITLE
Ajouter la possibilité d'ajouter des commentaires privés sur les devis 

### ISSUE THREAD

**Issue by shordeaux** [EtincelleCoworking/intranet#50]
l'idée est de pouvoir ajouter des notes au fur et à mesure des échanges avec le client sur les différentes demandes ou les relances à faire. a voir si cela a du sens de mettre une notion de "next step" avec une deadline pour faciliter le suivi

**Comment by redfish31** [comment]
Faire un "php artisan migrate" 
ping @shordeaux
