### ISSUE TITLE
date de création non modifiée

### ISSUE THREAD

**Issue by shordeaux** [EtincelleCoworking/intranet#71]
J'ai beau modifier la date de création d'un devis passé en facture, cela ne change pas dans la liste des factures et elle n'est pas bien triée du coup (cf. facture leroy merlin du 12/03/2015)

**Comment by JasonGallet** [comment]
J'ai fait une PR, donc à merge puis à tester (ca va avec le ticket #68 aussi du coup?)

**Comment by shordeaux** [comment]
la PR semble correspondre au #68, mais pas traiter ce ticket

**Comment by JasonGallet** [comment]
J'ai fait une autre PR pour ce ticket
