### ISSUE TITLE
ajouter une section avec le total des factures en attente de paiement

### ISSUE THREAD

**Issue by shordeaux** [EtincelleCoworking/intranet#87]
SELECT sum(invoices_items.amount) as amount FROM `invoices` join invoices_items on invoices.id = invoices_items.invoice_id WHERE invoices.date_payment is null AND invoices.type = 'F'

**Comment by redfish31** [comment]
Sur le dashboard ?

**Comment by shordeaux** [comment]
oui par ex. dans une nouvelle boite dans la première colonne

**Comment by redfish31** [comment]
ça pourrait se mettre sous le CA comme pour les charges ?
CA du mois X€
dont reste dû X€

**Comment by shordeaux** [comment]
sauf que c'est pas dont parce que ce n'est pas forcément sur le mois en cours, plutôt dans une autre boite, c'est utilisé pour autre chose, les 2 première pour piloter la rentabilité au quotidien, la dernière pour le recouvrement
