### ISSUE TITLE
Impossible de sauvegarder les modifications sur un utilisateur

### ISSUE THREAD

**Issue by shordeaux** [EtincelleCoworking/intranet#88]

**Comment by redfish31** [comment]
Est-ce que tu as fait un "php artisan migrate" ?

**Comment by shordeaux** [comment]
Re,

> Xavier Labeur <mailto:notifications@github.com>
> 31 mars 2015 17:16
>
> Est-ce que tu as fait un "php artisan migrate" ?
>
oui, qui c'est bien passé.

A bientôt,
Sébastien Hordeaux
--
WaterProof SARL - 10, rue de la comédie - 82000 Montauban
Tél: 05 63 66 96 27 - Fax: 05 63 66 96 26

**Comment by redfish31** [comment]
Je ne comprends pas, chez moi je peux modifier les utilisateurs sans aucun problème.
Est-ce que tu as un champs en particulier qui ne fonctionne pas ?
